spring.application.name=tictactoe
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/tictactoe?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
